import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainHeader from "@/components/header/main-header";
import {UserProvider} from "@auth0/nextjs-auth0/client";
import StoreProvider from "./StoreProvider";
import {ColorSchemeScript, MantineProvider} from '@mantine/core';
import '@mantine/core/styles.css';
import {HeaderSearch} from "@/components/header/header-search";
import {Main} from "next/document";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <StoreProvider>
            <head>
                <ColorSchemeScript/>
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >

            <MantineProvider defaultColorScheme="dark">
                 <MainHeader />
                {children}
            </MantineProvider>
            </body>
        </StoreProvider>
        </html>
    );
}
